ddi: client: replace deprecated aiohttp.Timeout
rauc/rauc-hawkbit pull request #7
Opened 2018-05-24 14:52 UTC by BastianStender

Use timeout keyword for session.get(), session.put() and
session.post(). Use async-timeout's context manager to allow content
reading just like before.

Signed-off-by: Bastian Stender <bst@pengutronix.de>

2018-06-06 08:44 UTC, ejoerns requested changes
Looks fine for me, except some minor indentations that should be adjusted.

2018-06-06 08:44 UTC, ejoerns commented on rauc_hawkbit/ddi/client.py
> +                                    timeout=self.timeout) as resp:
It was two indentation levels before and is only one now, thus please also fix indention of the block below

2018-06-06 08:44 UTC, ejoerns commented on rauc_hawkbit/ddi/client.py
> +                                    timeout=timeout) as resp:
same here as above

2018-06-06 08:44 UTC, ejoerns commented on rauc_hawkbit/ddi/client.py
> +                                     timeout=self.timeout) as resp:
here

2018-06-06 08:44 UTC, ejoerns commented on rauc_hawkbit/ddi/client.py
> +                                    timeout=self.timeout) as resp:
and here :)

2018-06-06 08:59 UTC, BastianStender commented
Good catch, fixed.

2019-03-15 13:36 UTC, ejoerns commented
I'll close this in favor of #8 which addressed the same issue but also enhances download speed by not limiting chunk sizes.

2019-03-15 13:36 UTC, closed without merging